### PR TITLE
Some changes

### PR DESCRIPTION
**Pull request by simonrenger**
Added some extra types and a github action to verify if it works

### CODE REVIEW

**Comment by ninkibah** [comment]
@simonrenger I'm not sure if you followed the whole twitter thread that inspired the creation of this repository, but I do want to keep one or two f the suggestions I got from other people. In particular, I loved char == fehrzeug. It took me a while to figure out what that meant, but it joke goes: fahrzeug => (direct translation to English) vehicle => (example vehicle) car => (same pronunciation in some idiolects) char.

I love your Protest and Protestausdruck! They are wonderful.

Finally, I think it would be better to keep the keywords lowercase, even if they are nouns.

**Comment by simonrenger** [comment]
No problem these were just suggestions not really meant to be merged merged :P Hence I was not completely sure where you were going with this this is why I made some suggestions :)

Again this Pr was ment to see what direction you intend to go so you could take what you wanted :)

> Finally, I think it would be better to keep the keywords lowercase, even if they are nouns.
Especially this was something I was not sure.

PS: Twitter threads are sometimes very confusing to follow therefore sorry that I did not see the joke :P otherweise yes I would have seen this and adjusted it accordingly :P

**Comment by simonrenger** [comment]
@ninkibah if you want to you can point out everything I shall change back or change in my PR and I can do it and you can merge it if you wanted to.

**Comment by ninkibah** [comment]
@simonrenger I'm now looking to use the material as part of a lightening talk I'd like to give at Meeting C++ 2022, when we meet in person again. Paul Targosz and Hendrik Niemeyer gave me encouragement in this direction. So, I'm looking for funny translations. That's why I liked fahrzeug.

But I also wondered how far I could go. So that's why I came up with #include <vektor> and so on.

On a serious note, I suppose it shows various techniques to use to change the names of keywords, namespaces, classes, functions and types. This might be interesting for people who deal with old ugly code.

**Comment by simonrenger** [comment]
> But I also wondered how far I could go. So that's why I came up with #include and so on.

This was why I translated the cstint file because it gives hideous long names (what else is German famous for! (anyone who has learned german at a german university with german c++ books will see ugly terms such as Vorzeichenloseganzahl (unsigned int) and than something like Vorzeichenloserganzahlzeiger (uintptr)

I guess in this case Schnur for string is perfect! and there are way more things you can use!

Protestausdruck for example is a good one. ^^

**Pull request closed without merging**
